version: "2.2"
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    networks:
      - elk-stack
    ports:
      - "9200:9200"
    stdin_open: true
    tty: true
  kibana:
    build: ./kibana
    container_name: kibana
    networks:
      - elk-stack
    depends_on:
      - elasticsearch
    ports: 
      - "5601:5601"
    stdin_open: true
    tty: true
  logstash:
    build: ./logstash
    container_name: logstash
    networks: 
      - elk-stack
    ports: 
      - "5000:5000"
    depends_on: 
      - elasticsearch
    stdin_open: true
    tty: true
networks:
  elk-stack:
    driver: bridge
